// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Autoharp
{
    internal sealed partial class Vsix
    {
        public const string Id = "Autoharp.1e989351-28fe-46b9-a875-f7cdf035b81c";
        public const string Name = "Autoharp";
        public const string Description = @"Autoharp solution navigator.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Cory Knapp";
        public const string Tags = "";
    }
}
