// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Autoharp
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string AutoharpString = "0c7b3a28-fa5f-45db-bf1d-9a2b6ac06ff4";
        public static Guid Autoharp = new Guid(AutoharpString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyCommandGroup = 0x1020;
        public const int PopNextCommand = 0x0100;
        public const int PopNextAndResetCommand = 0x0110;
    }
}