// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace Autoharp
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PopToRelatedFileString = "0c7b3a28-fa5f-45db-bf1d-9a2b6ac06ff4";
        public static Guid PopToRelatedFile = new Guid(PopToRelatedFileString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int PopNextAndResetCommand = 0x0110;
        public const int PopNextCommand = 0x0100;
    }
}